services:
  node-server:
    image: node:18
    ports: 
      - "3000:3000"
    volumes:
      - './Frontend:/usr/src/app'
    working_dir: '/usr/src/app'
    command: bash -c "npm install && npm start"
    environment:
      - NODE_ENV=production